version: '3.8'

services:
  mongodb:
    image: mongod-on-smb
    restart: always
    build:
        context: ./compose/local/mongodb
        dockerfile: Dockerfile
    container_name: mongodb
    ports:
      - "27017:27017"
    command: --config /etc/mongod.conf
    security_opt:
     - label=disable
    volumes:
     - type: bind
       source: /mnt/sandboxdb
       target: /data/db
