version: '3.8'

services:
  mongodb:
    image: mongo-on-smb
    init: true
    restart: always
    build:
        context: ./compose/local/mongodb
        dockerfile: Dockerfile
    container_name: mongodb
    cap_add:
      - CAP_SYS_ADMIN
    devices:
      - /dev/fuse
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
    command: --config /etc/mongod.conf