version: '3.8'

services:
  testing-mongodb:
    image: testing-mongod-on-smb
    restart: always
    build:
        context: ./compose/local/mongodb
        dockerfile: Dockerfile
    container_name: testing-mongodb
    command: --config /etc/mongod.conf
    security_opt:
     - label=disable
    volumes:
     - type: bind
       source: /mnt/sandboxdb/DB
       target: /data/db
     - type: bind
       source: /mnt/backup
       target: /data/backup
