version: '3.8'

services:
  mongodb:
    image: mongod-on-smb
    restart: always
    build:
        context: ./compose/local/mongodb
        dockerfile: Dockerfile
    container_name: mongodb
    cap_add:
      - CAP_SYS_ADMIN
    devices:
      - /dev/fuse
    expose:
      - "27017"
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb/username
    #  MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb/password
    command: --config /etc/mongod.conf